"""AI assistant + code generator endpoints."""
from fastapi import APIRouter, HTTPException

from ..services.ai_assistant import generate_code, get_assistant

router = APIRouter(prefix="/api/ai", tags=["ai"])


@router.post("/chat")
def chat(payload: dict):
    text = (payload.get("message") or "").strip()
    mode = payload.get("mode", "auto")
    if not text:
        raise HTTPException(400, "message required")
    return get_assistant().chat(text, mode)


@router.get("/history")
def history():
    return {"history": get_assistant().history()}


@router.post("/generate")
def generate(payload: dict):
    desc = (payload.get("description") or "").strip()
    if not desc:
        raise HTTPException(400, "description required")
    return generate_code(desc)


@router.post("/generate/save")
def save_code(payload: dict):
    from ..services.project_service import get_projects

    name = payload.get("name", "Generated Project")
    desc = payload.get("description", "Generated by Empire Code Generator")
    code = payload.get("code", "")
    proj = get_projects().create(name=name, description=desc, payload={"code": code})
    return {"ok": True, "id": proj["id"]}