"""Project management service (CRUD). Projects store a JSON payload."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Dict, List, Optional

from sqlalchemy import select

from ..db import SessionLocal
from ..models import Project
from .event_bus import emit_event

DEFAULT_PROJECTS = [
    {
        "name": "Gesture Controlled LEDs",
        "description": "Control up to four LEDs with hand gestures using the vision pipeline.",
        "payload": {
            "components": ["arduino_uno", "led", "led", "led", "led"],
            "pins": [{"name": "LED 1", "pin": "D13"}, {"name": "LED 2", "pin": "D12"},
                     {"name": "LED 3", "pin": "D11"}, {"name": "LED 4", "pin": "D10"}],
            "gestures": ["ONE_FINGER -> LED1_ON", "TWO_FINGERS -> LED2_ON",
                         "THREE_FINGERS -> LED3_ON", "FOUR_FINGERS -> LED4_ON"],
            "code": "// see firmware examples",
            "circuit": {},
            "notes": "Uses the default gesture mapping.",
        },
    },
    {
        "name": "Smart Distance Alarm",
        "description": "Buzzer alarm when an object comes closer than a threshold (HC-SR04).",
        "payload": {
            "components": ["arduino_uno", "hcsr04", "buzzer"],
            "pins": [{"name": "TRIG", "pin": "D9"}, {"name": "ECHO", "pin": "D10"}, {"name": "BUZZER", "pin": "D8"}],
            "gestures": [],
            "code": "// generated by Empire Code Generator",
            "circuit": {},
            "notes": "Threshold configurable in code.",
        },
    },
    {
        "name": "Temperature Monitor",
        "description": "Monitor temperature and humidity with a DHT22 and show readings on an OLED.",
        "payload": {
            "components": ["arduino_uno", "dht22", "oled"],
            "pins": [{"name": "DATA", "pin": "D2"}, {"name": "SDA", "pin": "A4"}, {"name": "SCL", "pin": "A5"}],
            "gestures": [],
            "code": "// DHT22 + SSD1306 example",
            "circuit": {},
            "notes": "Uses I2C for the display.",
        },
    },
    {
        "name": "Automatic Night Light",
        "description": "Turns on an LED when ambient light drops below a threshold (LDR).",
        "payload": {
            "components": ["arduino_uno", "ldr", "led", "resistor"],
            "pins": [{"name": "LDR", "pin": "A0"}, {"name": "LED", "pin": "D9"}],
            "gestures": [],
            "code": "// LDR night light example",
            "circuit": {},
            "notes": "Adds hysteresis to avoid flicker.",
        },
    },
    {
        "name": "Motion Detection System",
        "description": "Motion-triggered relay control using a PIR sensor.",
        "payload": {
            "components": ["arduino_uno", "pir", "relay"],
            "pins": [{"name": "PIR OUT", "pin": "D2"}, {"name": "RELAY", "pin": "D7"}],
            "gestures": [],
            "code": "// PIR relay example",
            "circuit": {},
            "notes": "Great starter for security automation.",
        },
    },
]


class ProjectService:
    def seed_defaults(self) -> None:
        with SessionLocal() as db:
            if db.query(Project).count() > 0:
                return
            for p in DEFAULT_PROJECTS:
                db.add(Project(name=p["name"], description=p["description"], payload=p["payload"]))
            db.commit()

    def list(self) -> List[dict]:
        with SessionLocal() as db:
            rows = db.scalars(select(Project).order_by(Project.updated_at.desc())).all()
        return [self._to_dict(r) for r in rows]

    def get(self, project_id: int) -> Optional[dict]:
        with SessionLocal() as db:
            row = db.get(Project, project_id)
            return self._to_dict(row) if row else None

    def create(self, name: str, description: str = "", payload: Optional[dict] = None) -> dict:
        with SessionLocal() as db:
            row = Project(name=name, description=description, payload=payload or {})
            db.add(row)
            db.commit()
            db.refresh(row)
            pid = row.id
        emit_event("SYSTEM", "Project created", "SUCCESS", name)
        return {"id": pid}

    def update(self, project_id: int, data: dict) -> Optional[dict]:
        with SessionLocal() as db:
            row = db.get(Project, project_id)
            if row is None:
                return None
            if "name" in data:
                row.name = data["name"]
            if "description" in data:
                row.description = data["description"]
            if "payload" in data:
                row.payload = data["payload"]
            db.commit()
            db.refresh(row)
        emit_event("SYSTEM", "Project updated", "SUCCESS", row.name)
        return self.get(project_id)

    def delete(self, project_id: int) -> bool:
        with SessionLocal() as db:
            row = db.get(Project, project_id)
            if row is None:
                return False
            db.delete(row)
            db.commit()
        emit_event("SYSTEM", "Project deleted", "INFO", str(project_id))
        return True

    @staticmethod
    def _to_dict(row: Project) -> dict:
        return {
            "id": row.id,
            "name": row.name,
            "description": row.description,
            "payload": row.payload or {},
            "created_at": row.created_at.isoformat(),
            "updated_at": row.updated_at.isoformat(),
        }


_project_service: Optional[ProjectService] = None


def get_projects() -> ProjectService:
    global _project_service
    if _project_service is None:
        _project_service = ProjectService()
        _project_service.seed_defaults()
    return _project_service